CREATE PROCEDURE DajMiejscowosciWPowiecie
AS
SELECT t.NAZWA, t.NAZWA_TERYTORIALNA, s.NAZWA AS MIEJSCOWO�C, s.SYMPOD
FROM TERC t
CROSS JOIN SIMC s
WHERE s.WOJEWODZTWO_ID = t.WOJEWODZTWO_ID 
AND t.POWIAT_ID = s.POWIAT_ID
AND s.SYMPOD > s.SYM_NUMER;
GO

-- EXEC DajMiejscowosciWPowiecie