CREATE PROCEDURE DajPowiaty
AS
SELECT WOJEWODZTWO_ID, POWIAT_ID, NAZWA, NAZWA_TERYTORIALNA, STAN_NA
  FROM [Terryt].[dbo].[TERC]
  WHERE POWIAT_ID != null AND GMINA_ID  = 0 AND RODZ_GMINA_ID = 0 AND NAZWA_TERYTORIALNA != 'województwo';
GO

-- EXEC DajPowiaty